# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1cb09dc0-51ba-4612-944e-1f61e715e553";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1cb09dc0-51ba-4612-944e-1f61e715e553".device = "/dev/disk/by-uuid/1cb09dc0-51ba-4612-944e-1f61e715e553";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4A8D-6447";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-0474b0fb-755d-4b08-85ff-704ae655c3bc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
